Allow case-insensitive matching of context dimension values
teemtee/fmf pull request #195
Opened 2023-07-24 20:23 UTC by therazix

Matching of context dimension values can now be case-insensitive by calling `fmf.Tree.adjust()` with the `case_sensitive=False` parameter. The default behavior remains case-sensitive.

I have also updated the documentation about the default behavior and added some tests.

Resolves: #186

2023-07-27 14:56 UTC, lukaszachy approved these changes

2023-08-09 13:39 UTC, psss requested changes
Thanks for implementing this! Looks good in general. I just propose a minor docs improvement in def9655 and added two questions.

2023-08-09 13:39 UTC, psss commented on fmf/context.py
> +                it_val, ordered=False, case_sensitive=self._case_sensitive) == 0
```suggestion
                it_val, ordered=False, case_sensitive=self.case_sensitive) == 0
```

Why not using the property directly?

2023-08-09 14:28 UTC, therazix commented on fmf/context.py
> +        return False
You are right. It should be changed now.

2023-09-26 11:42 UTC, therazix commented
Somehow I missed that child nodes were not adjusted. This should be fixed in 99f608b.

2023-09-29 15:40 UTC, psss approved these changes
Looks good now, thanks!

2023-09-29 16:39 UTC, merged